"use strict";

exports.ENUM_KIND_VARIABLE = [
  Core.KIND_VARIABLE_VOID,
  Core.KIND_VARIABLE_VAR,
  Core.KIND_VARIABLE_FUNCTION,
  Core.KIND_VARIABLE_PARAM,
  Core.KIND_VARIABLE_LET,
  Core.KIND_VARIABLE_CONST
  Core.KIND_VARIABLE_CLASS];

exports.ENUM_KIND_VARIABLE_BLOCK = [
  Core.KIND_VARIABLE_LET,
  Core.KIND_VARIABLE_CONST
  Core.KIND_VARIABLE_CLASS];

exports.ENUM_KIND_LABEL = [
  Core.KIND_LABEL_BREAK,
  Core.KIND_LABEL_CONTINUE];

exports.ENUM_KIND_MARKER_STRICT = [
  Core.KIND_MARKER_WITH,
  Core.KIND_MARKER_DISCARD,
  Core.KIND_MARKER_PATTERN_EVAL,
  Core.KIND_MARKER_PATTERN_ARGUMENTS];
